# -*- coding: utf-8 -*-
"""mainwork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLiHdUiEuX8dXoNxrRtQA_vxKbeVxc6k
"""

import pandas as pd

data = pd.read_csv('/content/work.csv')

data.head(10)

import sklearn
from sklearn.tree import DecisionTreeClassifier as dt
from sklearn.model_selection import train_test_split

datasub = data[['Age','EstimatedSalary','Purchased']]
datasub.head(5)

X = datasub[['Age','EstimatedSalary']]
y = datasub['Purchased']
X_train,X_test,y_train,y_test = train_test_split(X,y,shuffle=False,test_size=0.2)
X_train

dtclf = dt()
dtclf.fit(X_train,y_train)

pred = dtclf.predict(X_test)

from sklearn.metrics import accuracy_score
print('accuracy is ',accuracy_score(pred,y_test))

from sklearn.metrics import classification_report

df = pd.DataFrame({'Actual':y_test,'Predicted':pred})

df

import matplotlib.pyplot as plt

df1 = df.head(25)
df1.plot(kind='bar',figsize=(20,10))
plt.grid(which='major' ,linestyle='-',linewidth='1', color='green')
plt.grid(which='minor' ,linestyle=':',linewidth='1', color='black')
plt.show()

